name: Release

on:
  release:
    types: [released]

jobs:
  update_tag:
    name: Update major tag
    runs-on: ubuntu-22.04
    env:
      TAG_NAME: ${{ github.event.release.tag_name }}
    steps:
      - name: Update the ${{ env.TAG_NAME }} tag
        uses: actions/publish-action@v0.2.2
        with:
          source-tag: ${{ env.TAG_NAME }}
